# Documentation for Sublime WP Customizer.
#
# Author: WPCouple (Ahmad Awais / Maedah Batool) and WPCTeam.
# License: Copyright ⓒ WPCouple.

site_name: Sublime WP Customizer

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ahmadawais/Sublime-WP-Customizer'

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
      icon: 'bookmark'
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
extra_css:
  - 'stylesheets/extra.css'
pages:
  - 1. INTRODUCTION: index.md
  - 2. GETTING STARTED: getting-started.md
  - 3. SNIPPETS REFERENCE: snippets.md
  - 4. IMPLEMENTATION:
        - Adding a Register Function: wordpress-customizer-snippets/add-register-function.md
        - Adding a Cutsomizer Panel: wordpress-customizer-snippets/add-panel.md
        - Adding a Customizer Section: wordpress-customizer-snippets/add-section.md
        - Adding a Customizer Setting: wordpress-customizer-snippets/add-setting.md
        - Adding a Customizer Control: wordpress-customizer-snippets/add-basic-control.md
        - Adding a Customizer Color: wordpress-customizer-snippets/add-control-color.md
        - Adding a Customizer Image: wordpress-customizer-snippets/add-control-image.md
        - Adding a Customizer Upload: wordpress-customizer-snippets/add-file-upload.md
  - 5. SYNTAX: eg.md

markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta




