# Documentation for Sublime WP Customizer.
#
# Author: WPCouple (Ahmad Awais / Maedah Batool) and WPCTeam.
# License: Copyright ⓒ WPCouple.

site_name: Sublime WP Customizer

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ahmadawais/Sublime-WP-Customizer'

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
      icon: 'bookmark'
  palette:
    primary: 'light blue'
    accent: 'indigo'
  font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
extra_css:
  - 'stylesheets/extra.css'
pages:
  - 1. START HERE: index.md
  - 2. INTRODUCTION: introduction.md
  - 3. GETTING STARTED: getting-started.md
  - 4. SNIPPETS: snippets.md
  - 5. IMPLEMENTATION:
        - Adding a Customizer Register Function: cust-reg-func.md
        - Adding a Cutsomizer Panel: cust-panel.md
        - Adding a Customizer Section: cust-section.md
        - Adding a Customizer Setting: cust-setting.md
        - Adding a Customizer Control: cust-basic-control.md
        - Adding a Customizer Color: cust-ctr-clr.md
        - Adding a Customizer Image: cust-ctr-img.md
        - Adding a Customizer Upload: cust-upload.md
  - 6. End: end.md
  - 7. SYNTAX: eg.md

markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta




